//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Leayal.SnowBreakLauncher.I18n {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Leayal.SnowBreakLauncher.I18n.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Bilibili 的本地化字符串。
        /// </summary>
        public static string Bilibili {
            get {
                return ResourceManager.GetString("Bilibili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Binary patching 的本地化字符串。
        /// </summary>
        public static string BinaryPatching {
            get {
                return ResourceManager.GetString("BinaryPatching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Browse 的本地化字符串。
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Browse for existing game client 的本地化字符串。
        /// </summary>
        public static string BrowseforExistingGameClient {
            get {
                return ResourceManager.GetString("BrowseforExistingGameClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Game client is being updated. Are you sure you want to cancel updating and close the launcher? 的本地化字符串。
        /// </summary>
        public static string CancelUpdate {
            get {
                return ResourceManager.GetString("CancelUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change Game Client Directory 的本地化字符串。
        /// </summary>
        public static string ChangeGameClientDirectory {
            get {
                return ResourceManager.GetString("ChangeGameClientDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Checking for game client updates 的本地化字符串。
        /// </summary>
        public static string CheckingGameClientUpdate {
            get {
                return ResourceManager.GetString("CheckingGameClientUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close 的本地化字符串。
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Game client is being updated. Are you sure you want to cancel updating and close the launcher? 的本地化字符串。
        /// </summary>
        public static string CloseLauncherWhenUpdating {
            get {
                return ResourceManager.GetString("CloseLauncherWhenUpdating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirmation 的本地化字符串。
        /// </summary>
        public static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detected your game client 的本地化字符串。
        /// </summary>
        public static string DetectedYourGameClient {
            get {
                return ResourceManager.GetString("DetectedYourGameClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Downloading 的本地化字符串。
        /// </summary>
        public static string Downloading {
            get {
                return ResourceManager.GetString("Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do you want to use this path? 的本地化字符串。
        /// </summary>
        public static string DoYouWantToUseThisPath {
            get {
                return ResourceManager.GetString("DoYouWantToUseThisPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable Streamer Mode 的本地化字符串。
        /// </summary>
        public static string EnableStreamerMode {
            get {
                return ResourceManager.GetString("EnableStreamerMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable Censorship 的本地化字符串。
        /// </summary>
        public static string EnableStreamerModeToolTip {
            get {
                return ResourceManager.GetString("EnableStreamerModeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error 的本地化字符串。
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File check and downloading 的本地化字符串。
        /// </summary>
        public static string FileDownloading {
            get {
                return ResourceManager.GetString("FileDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The game is already running 的本地化字符串。
        /// </summary>
        public static string GameAlreadyRunning1 {
            get {
                return ResourceManager.GetString("GameAlreadyRunning1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Game already running 的本地化字符串。
        /// </summary>
        public static string GameAlreadyRunning2 {
            get {
                return ResourceManager.GetString("GameAlreadyRunning2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Game Client File 的本地化字符串。
        /// </summary>
        public static string GameClientFile {
            get {
                return ResourceManager.GetString("GameClientFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Your game client seems to be out-dated. Do you want to update it now? 的本地化字符串。
        /// </summary>
        public static string GameNeedUpdate {
            get {
                return ResourceManager.GetString("GameNeedUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ☁ 的本地化字符串。
        /// </summary>
        public static string GamePreDownLoad {
            get {
                return ResourceManager.GetString("GamePreDownLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pre-download updates 的本地化字符串。
        /// </summary>
        public static string GamePreDownLoadToolTip {
            get {
                return ResourceManager.GetString("GamePreDownLoadToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Server Selector 的本地化字符串。
        /// </summary>
        public static string GameServerSelector {
            get {
                return ResourceManager.GetString("GameServerSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Global 的本地化字符串。
        /// </summary>
        public static string Global {
            get {
                return ResourceManager.GetString("Global", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Information 的本地化字符串。
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The launcher cannot find your game client. Please choose these options: 的本地化字符串。
        /// </summary>
        public static string InstallGame {
            get {
                return ResourceManager.GetString("InstallGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 - Cancel: Abort and go back. 的本地化字符串。
        /// </summary>
        public static string InstallGameCancel {
            get {
                return ResourceManager.GetString("InstallGameCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 - No: Browse for your existing game client. 的本地化字符串。
        /// </summary>
        public static string InstallGameNo {
            get {
                return ResourceManager.GetString("InstallGameNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 - Yes: Select a folder to install the game to. 的本地化字符串。
        /// </summary>
        public static string InstallGameYes {
            get {
                return ResourceManager.GetString("InstallGameYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Install or select existing game files 的本地化字符串。
        /// </summary>
        public static string InstallorSelectGameFile {
            get {
                return ResourceManager.GetString("InstallorSelectGameFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid item selected 的本地化字符串。
        /// </summary>
        public static string InvalidItemSelected {
            get {
                return ResourceManager.GetString("InvalidItemSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Jinshan 的本地化字符串。
        /// </summary>
        public static string Jinshan {
            get {
                return ResourceManager.GetString("Jinshan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You need to restart the application manually to change the language. 的本地化字符串。
        /// </summary>
        public static string LanguageChanged {
            get {
                return ResourceManager.GetString("LanguageChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Events 的本地化字符串。
        /// </summary>
        public static string LauncherNewsEvents {
            get {
                return ResourceManager.GetString("LauncherNewsEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Notices 的本地化字符串。
        /// </summary>
        public static string LauncherNewsNotices {
            get {
                return ResourceManager.GetString("LauncherNewsNotices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change Launcher Settings 的本地化字符串。
        /// </summary>
        public static string LauncherSettings {
            get {
                return ResourceManager.GetString("LauncherSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ⚙ 的本地化字符串。
        /// </summary>
        public static string LauncherSettingsMenu {
            get {
                return ResourceManager.GetString("LauncherSettingsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Launcher settings 的本地化字符串。
        /// </summary>
        public static string LauncherSettingsMenuToolTip {
            get {
                return ResourceManager.GetString("LauncherSettingsMenuToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Launcher Settings 的本地化字符串。
        /// </summary>
        public static string LauncherSettingsTitle {
            get {
                return ResourceManager.GetString("LauncherSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SnowBreak: Containment Zone Game Launcher 的本地化字符串。
        /// </summary>
        public static string LauncherTitle {
            get {
                return ResourceManager.GetString("LauncherTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loading launcher UI 的本地化字符串。
        /// </summary>
        public static string LauncherUILoading {
            get {
                return ResourceManager.GetString("LauncherUILoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Launcher version:  的本地化字符串。
        /// </summary>
        public static string LauncherVersion {
            get {
                return ResourceManager.GetString("LauncherVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 It seems you haven&apos;t installed the game yet or the launcher doesn&apos;t know where it is. 的本地化字符串。
        /// </summary>
        public static string LetUserKnowGameDirectoryIsNotSetForThisFunction1 {
            get {
                return ResourceManager.GetString("LetUserKnowGameDirectoryIsNotSetForThisFunction1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please install or select the game data location before performing this action. 的本地化字符串。
        /// </summary>
        public static string LetUserKnowGameDirectoryIsNotSetForThisFunction2 {
            get {
                return ResourceManager.GetString("LetUserKnowGameDirectoryIsNotSetForThisFunction2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loading launcher UI... 的本地化字符串。
        /// </summary>
        public static string LoadingLauncherUI {
            get {
                return ResourceManager.GetString("LoadingLauncherUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Downloading manifest from remote host 的本地化字符串。
        /// </summary>
        public static string ManifestDownloading {
            get {
                return ResourceManager.GetString("ManifestDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (The path above is not missing anything, it is where the &apos;manifest.json&apos; file supposed to be) 的本地化字符串。
        /// </summary>
        public static string ManifestJsonExplain1 {
            get {
                return ResourceManager.GetString("ManifestJsonExplain1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (If the path doesn&apos;t look like what you desired, please move the folder and select the relocated folder) 的本地化字符串。
        /// </summary>
        public static string ManifestJsonExplain2 {
            get {
                return ResourceManager.GetString("ManifestJsonExplain2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The file you selected is not a local file on your machine 的本地化字符串。
        /// </summary>
        public static string NotLocalFile {
            get {
                return ResourceManager.GetString("NotLocalFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The file you selected doesn&apos;t seem to be the expected SnowBreak game client file 的本地化字符串。
        /// </summary>
        public static string NotSnowbreakGameFile {
            get {
                return ResourceManager.GetString("NotSnowbreakGameFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Game Data Directory 的本地化字符串。
        /// </summary>
        public static string OpenGameDataDirectory {
            get {
                return ResourceManager.GetString("OpenGameDataDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This action Your OS is not supported. Something went wrong!!! 的本地化字符串。
        /// </summary>
        public static string OSnotSupport {
            get {
                return ResourceManager.GetString("OSnotSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preparing 的本地化字符串。
        /// </summary>
        public static string Preparing {
            get {
                return ResourceManager.GetString("Preparing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Prompt 的本地化字符串。
        /// </summary>
        public static string Prompt {
            get {
                return ResourceManager.GetString("Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (Click to open original releases page, Edit by LemonPAKA) 的本地化字符串。
        /// </summary>
        public static string ReleasesPage {
            get {
                return ResourceManager.GetString("ReleasesPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Game is running... 的本地化字符串。
        /// </summary>
        public static string RunningGame {
            get {
                return ResourceManager.GetString("RunningGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select a folder to install the game to 的本地化字符串。
        /// </summary>
        public static string SelectInstallPath1 {
            get {
                return ResourceManager.GetString("SelectInstallPath1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The path to the folder you selected is not a local path. 的本地化字符串。
        /// </summary>
        public static string SelectInstallPath2 {
            get {
                return ResourceManager.GetString("SelectInstallPath2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The path you specified doesn&apos;t exist. Create destination folder? 的本地化字符串。
        /// </summary>
        public static string SelectInstallPath3 {
            get {
                return ResourceManager.GetString("SelectInstallPath3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detected your game client: 的本地化字符串。
        /// </summary>
        public static string SelectInstallPath4 {
            get {
                return ResourceManager.GetString("SelectInstallPath4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do you want to use this path? 的本地化字符串。
        /// </summary>
        public static string SelectInstallPath5 {
            get {
                return ResourceManager.GetString("SelectInstallPath5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (The path above is not missing anything, it is where the &apos;manifest.json&apos; file supposed to be) 的本地化字符串。
        /// </summary>
        public static string SelectInstallPath6 {
            get {
                return ResourceManager.GetString("SelectInstallPath6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Destination to install SnowBreak game client: 的本地化字符串。
        /// </summary>
        public static string SelectInstallPath7 {
            get {
                return ResourceManager.GetString("SelectInstallPath7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do you want to install the game to this destination? 的本地化字符串。
        /// </summary>
        public static string SelectInstallPath8 {
            get {
                return ResourceManager.GetString("SelectInstallPath8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start game 的本地化字符串。
        /// </summary>
        public static string StartGame {
            get {
                return ResourceManager.GetString("StartGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 It seems like the configuration has changed. 的本地化字符串。
        /// </summary>
        public static string StartGameLocationCheck1 {
            get {
                return ResourceManager.GetString("StartGameLocationCheck1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do you want to use the path from the configuration file (see below)? 的本地化字符串。
        /// </summary>
        public static string StartGameLocationCheck2 {
            get {
                return ResourceManager.GetString("StartGameLocationCheck2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Game is starting... 的本地化字符串。
        /// </summary>
        public static string StartingGame {
            get {
                return ResourceManager.GetString("StartingGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown version 的本地化字符串。
        /// </summary>
        public static string UnknownVersion {
            get {
                return ResourceManager.GetString("UnknownVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update game client 的本地化字符串。
        /// </summary>
        public static string UpdateGameClient {
            get {
                return ResourceManager.GetString("UpdateGameClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Downloading manifest from remote host 的本地化字符串。
        /// </summary>
        public static string UpdateingGame {
            get {
                return ResourceManager.GetString("UpdateingGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Updating game client 的本地化字符串。
        /// </summary>
        public static string UpdatingGameClient {
            get {
                return ResourceManager.GetString("UpdatingGameClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Allow fetching manifest data from official launcher 的本地化字符串。
        /// </summary>
        public static string UseManifestFromOfficialLauncher {
            get {
                return ResourceManager.GetString("UseManifestFromOfficialLauncher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Allow this launcher to fetch the resource manifest data (this data is used to locate the game client&apos;s files) from official launcher. This may result in partial launcher downloads 的本地化字符串。
        /// </summary>
        public static string UseManifestFromOfficialLauncherToopTip {
            get {
                return ResourceManager.GetString("UseManifestFromOfficialLauncherToopTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use secure DNS Resolver (Cloudflare DNS over HTTPS) 的本地化字符串。
        /// </summary>
        public static string UseSecureDNSResolver {
            get {
                return ResourceManager.GetString("UseSecureDNSResolver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use secure DNS Resolver (Cloudflare DNS over HTTPS)&quot; ToolTip.Tip=&quot;Use secure DNS protocol to resolve domain names into IP addresses (specifically, DNS over HTTPS). Secure DNS server provider is Cloudflare (specifically, 1.1.1.1) 的本地化字符串。
        /// </summary>
        public static string UseSecureDNSResolverToolTip {
            get {
                return ResourceManager.GetString("UseSecureDNSResolverToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use a Unix filename 的本地化字符串。
        /// </summary>
        public static string UseUnixfilename {
            get {
                return ResourceManager.GetString("UseUnixfilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 In the nutshell, this is similar to emulate the behavior of File Explorer of Windows operating system. Launch the game directly using File Explorer 的本地化字符串。
        /// </summary>
        public static string UseUnixfilenameToolTip {
            get {
                return ResourceManager.GetString("UseUnixfilenameToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Allow using memory space instead of disk 的本地化字符串。
        /// </summary>
        public static string UsingMemoryInsteadOfDisk {
            get {
                return ResourceManager.GetString("UsingMemoryInsteadOfDisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Allow launcher to partially download official launcher into memory instead of into disks 的本地化字符串。
        /// </summary>
        public static string UsingMemoryInsteadOfDiskToolTip {
            get {
                return ResourceManager.GetString("UsingMemoryInsteadOfDiskToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scan And Fix Missing Or Damaged Game Data 的本地化字符串。
        /// </summary>
        public static string VerifyGameIntegrity {
            get {
                return ResourceManager.GetString("VerifyGameIntegrity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to begin file integrity check and download missing/damaged files? 的本地化字符串。
        /// </summary>
        public static string VerifyGameIntegrityConfirm {
            get {
                return ResourceManager.GetString("VerifyGameIntegrityConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (This action will take a short time or long time, depending on your disk&apos;s speed) 的本地化字符串。
        /// </summary>
        public static string VerifyGameIntegrityExplain {
            get {
                return ResourceManager.GetString("VerifyGameIntegrityExplain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wine location 的本地化字符串。
        /// </summary>
        public static string Winelocation {
            get {
                return ResourceManager.GetString("Winelocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The path to wine executable. Can be empty path to auto-detect system-installed wine 的本地化字符串。
        /// </summary>
        public static string WinelocationToolTip {
            get {
                return ResourceManager.GetString("WinelocationToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wine Settings 的本地化字符串。
        /// </summary>
        public static string WineSettingsTitle {
            get {
                return ResourceManager.GetString("WineSettingsTitle", resourceCulture);
            }
        }
    }
}
